name: chatter-backend
services:
    webapp:
        image: chat-ws-api:local
        build:
            context: ./
            dockerfile: Dockerfile
        environment:
            - SPRING_PROFILES_ACTIVE=localDocker
        deploy:
            mode: replicated
            replicas: 3
            resources:
                reservations:
                    cpus: '0.50'
                    memory: 1024M
                limits:
                    cpus: '0.50'
                    memory: 1024M
        volumes:
            - ./clustered:/home/appuser/clustered
    nginx:
        image: nginx:1.27-alpine
        ports:
            - "9090:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
    docker-mysql:
        image: mysql:8.4-oraclelinux9
        restart: always
        ports:
            - 33060:3306
        environment:
            MYSQL_ROOT_PASSWORD: donotuseinproduction
            TZ: Asia/Seoul
        deploy:
            resources:
                reservations:
                    cpus: '0.50'
                    memory: 1024M
                limits:
                    cpus: '0.50'
                    memory: 1024M
        volumes:
            - ./db/mysql/data:/var/lib/mysql
            - ./db/mysql/init:/docker-entrypoint-initdb.d
            - ./db/mysql/mysql-init-files/:/docker-entrypoint-initdb.d
