name: chatter-backend
services:
    webapp:
        image: chat-ws:local
        build:
            context: ./
            dockerfile: Dockerfile
        deploy:
            mode: replicated
            replicas: 3
            resources:
                reservations:
                    cpus: '0.50'
                    memory: 1024M
                limits:
                    cpus: '0.50'
                    memory: 1024M
        volumes:
            - ./clustered:/home/appuser/clustered
    nginx:
        image: nginx:1.27-alpine
        ports:
            - "9090:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
