logging:
    level:
        root: info
        com.example.chatter: debug

spring:
    application:
        name: chat-backend-local
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:homeworkDB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=3000
        username: sa
        password: sa
        hikari:
            pool-name: homework-pool
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true
            path: /h2-console
    threads:
        virtual:
            enabled: true


camel:
    component:
        hazelcast-topic:
            hazelcast-mode: client
    cluster:
        file:
            enabled: true
            id: ${random.uuid}
            root: ./clustered
        controller:
            enabled: true
            namespace: lock2
            routes[heartbeat]:
                clustered: false
    main:
        dev-console-enabled: true
        name: camel-chat-backend-local
